spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/springcloudsell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8082
mybatis:
  type-aliases-package: com.springclouddemo.user.domain
  mapper-locations: classpath:mapper/*.xml
