spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
zuul:
  #  全局cookie透传
  sensitive-headers:
  routes:
  # /myProduct/product/list -> /product/product/list
    myProduct:
      path: /myProduct/**
      serviceId: product
      # cookie
      sensitiveHeaders:
